### ISSUE TITLE
这个学生管理系统相当不错，也可以看下这个系统，可以演示

### ISSUE THREAD

**Issue by zhangtianjiaoxyz** [LGSKOKO/Student-dormitory-management-system#3]
https://www.icodedock.com/article/category/student.html 这个

**Comment by LGSKOKO** [comment]
你这波操作  骚啊，把自己做的东西放在自己的网站上，但是是收费的，然后来我的项目下留评论  贴你的网站，钓鱼评论？

**Comment by zhangtianjiaoxyz** [comment]
可以入驻

**Comment by LGSKOKO** [comment]
> https://www.icodedock.com/article/category/student.html 这个

你这波操作 骚啊，把自己做的东西放在自己的网站上，但是是收费的，然后来我的项目下留评论 贴你的网站增加曝光率吗，钓鱼评论？
